"""Run labeled example questions, print routing accuracy, and write examples.md.

Usage: python examples.py
"""

from main import MODEL, answer_from_dataset, select_dataset

# (question, expected dataset, what the case tests)
EXAMPLES = [
    ("What is the average spending score for female vs male customers?", "shopping_habits", "clear shopping"),
    ("Which age group spends the most?", "shopping_habits", "clear shopping"),
    ("Is there a relationship between annual income and spending score?", "shopping_habits", "clear shopping"),
    ("Which programming language is searched the most overall?", "weekly_searches", "clear searches"),
    ("What happened to programming language searches in late December 2023?", "weekly_searches", "clear searches"),
    ("Is interest in C++ growing or declining?", "weekly_searches", "clear searches"),
    ("What is the capital of France?", "none", "off-topic"),
    ("Do older customers search for Python more?", "none", "needs both datasets"),
    ("Which week had the highest score for Java?", "weekly_searches", "tricky: 'score' is a shopping column name"),
    ("Are our big earners also our big spenders?", "shopping_habits", "tricky: no column names used"),
]


def main() -> None:
    correct = 0
    sections = []

    for question, expected, case in EXAMPLES:
        selection = select_dataset(question)
        answer = answer_from_dataset(question, selection)

        is_correct = selection["dataset"] == expected
        correct += is_correct
        print(f"[{'PASS' if is_correct else 'FAIL'}] {question} -> {selection['dataset']} (expected {expected})")

        sections.append(
            f"## {question}\n\n"
            f"- **Case:** {case}\n"
            f"- **Expected dataset:** `{expected}`\n"
            f"- **Routed dataset:** `{selection['dataset']}` ({'correct' if is_correct else 'WRONG'})\n"
            f"- **Router reasoning:** {selection['reasoning']}\n\n"
            f"**Answer:**\n\n{answer}\n"
        )

    accuracy = f"{correct}/{len(EXAMPLES)}"
    print(f"\nRouting accuracy: {accuracy}")

    header = (
        "# Example runs\n\n"
        f"Generated by `python examples.py` with model `{MODEL}`.\n\n"
        f"**Routing accuracy: {accuracy}**\n\n"
    )
    with open("examples.md", "w") as f:
        f.write(header + "\n".join(sections))


if __name__ == "__main__":
    main()
